baseURL = 'https://ferdi4.github.io/herzbar-menu/'

defaultContentLanguage = "de"
theme = "reveal-hugo"

[languages]
[languages.de]
title = "HERZ bar&lounge"
[languages.en]
title = "HERZ bar&lounge"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[author]
name = "Ferdinand Bauer"

[params.reveal_hugo]
history = true
center = false
width = 800
height = 1400
load_default_plugins = false
custom_theme = "herzbar-theme.scss"
custom_theme_compile = true
