baseURL = 'https://ferdi4.github.io/herzbar-menu/'
languageCode = 'de-de'
title = 'HERZ bar&lounge'

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[author]
name = "Ferdinand Bauer"

[params.reveal_hugo]
history = true
center = false
width = 800
height = 1400
theme="moon"
load_default_plugins = false
