baseURL = 'https://ferdi4.github.io/herzbar-menu/'
languageCode = 'de-de'
title = 'HERZ bar&lounge'

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
